[font]
size = 14.0

[font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

[window]
padding = { x = 4, y = 4 }
opacity = 0.98

[colors.primary]
background = "#151f20"
foreground = "#cdd6f4"
